export const labels = {
  login: "login",
  signIn: "Sign In",
  welcomeBack: "Welcome Back",
  PleaseEnterYourDetails: "Please, enter your details.",
  email: "Email",
  cancel: "Cancel",
  password: "Password",
  forgetPassword: "Forgot password?",
  orContinueWith: "Or continue with",
  SignUp: "sign up",
  dontHaveAnAccount: "Don’t have an account?",
  contributor: "Contributor",
  measure: "Measure (Units)",
  updatedBY: "Updated By",
  url: "Url",
  clickHereSeeBudget: "Click Here to see Budget",
  budgetDetails: "Budget Details",
  clientList: "Client List",
  name: "Name",
  projectMember: "Project Member",
  addNewBudget: "Add New Budget",
  addContributor: "Add Contributor",
  emailNotifications: "Email Notifications",
  budgetDeleted: "Budget Deleted",
  attachment: "Attachment",
  seeAttachment: "See Attachment",
  addFileAttachment: "Add File Attachment (Optional)",
  loadMore: "Load More",
  createYourAccount: "Create your account",
  areYouSureYouWantToDelete: "Are you sure you want to delete this project?",
  areYouSureYouWantToDeleteUser: "Are you sure you want to delete this user?",
  areYouSureYouWantToDeleteThis: "Are you sure you want to delete this.",
  areYouSureYouWantToDeleteTask: "Are you sure you want to delete this task?",
  pleaseenteryourdetails: "Please, enter your information to sign up",
  alreadyhaveaccount: "Already have an account?",
  enteryouremailtorecieveverification:
    "Please, enter your email address to receive a verification code",
  backToLogin: "Back To Log In",
  send: "Send",
  changeStatusSuccess: "Changed Status Successfully!",
  resendCode: "Resend Code",
  dateError: "Start date can't be greater than due date.",
  newEmail: "Type new Email",
  dateError: "Start date can't be greater than due date.",
  budgetDescription: "Description",
  budgetAmount: "Amount",
  delete: "Delete",
  verify: "verify",
  verifyemail: "Verify Your Email",
  socialLoginSuccessfull: "Social Login Successfull!",
  invalidURL: "Invalid Url",
  save: "Save",
  editTask: "Edit Task",
  activity: "Activity",
  pleaseenterthecodesentto: "Please, enter the 4 digit code sent to",
  verifyemailsend: "johndoe@soloway.com",
  createNewPassword: "Create New Password",
  yournewPasswordMustcontain:
    "Your new password must contain at least 8 characters containing both letters and numbers.",
  newPassword: "New Password",
  confirmationPassword: "Confirmation Password",
  resetPassword: "Reset Password",
  enterYourEmail: "Enter your email",
  success: "Success",
  yourPasswordhasBeenReset: "Your password has been successfully reset",
  all: "All",
  inProgress: "In Progress",
  blocked: "Blocked",
  completed: "Completed",
  users: "Users",
  user: "User",
  newUser: "New User",
  search: "Search",
  assign: "Assign",
  addNewUser: "Add New User",
  addNewProject: "Add New Project",
  firstName: "First Name",
  lastName: "Last Name",
  role: "Role",
  userName: "User Name",
  sendInvite: "Send Invite",
  seanKingstom: "Sean Kingstom",
  noInternetConnection: "No Internet Connection",
  admin: "Admin",
  client: "Client",
  actions: "Actions",
  yourFullName: "Your Full Name",
  member: "Member",
  soloway: "Soloway",
  tucson: "Tucson",
  evoDesign: "Evo Design",
  filter: "Filter",
  taskTitle: "Task Title",
  responsible: "Responsible",
  status: "Status",
  notStarted: "Not Started",
  startDate: "Start Date",
  clearAll: "Clear All",
  saveFilters: "Save Filters",
  logOutSuccess: "Logout Success",
  project: "Projects",
  newProject: "New Project",
  projectName: "Project Name",
  dueDate: "Due Date",
  clientName: "Client Name",
  create: "Create",
  addMembers: "Add members",
  yourEmail: "Your Email",
  changeView: "Change View",
  Blocked: "Blocked",
  assignee: "Assignee",
  comments: "Comments",
  estimatedCompletion: "Estimated Completion",
  newHouseProject: "New House Project",
  saveChanges: "Save Changes",
  setting: "Setting",
  profile: "Profile",
  preferences: "Preferences",
  personalInfo: "Personal Information",
  userEmail: "sean@soloway.com",
  address: "Address",
  userAddress: "User Address",
  postalCode: "Postal Code",
  cityName: "City Name",
  countryName: "Country Name",
  twoFactorAuthentication: "2-factor Authentication",
  cellNo: "Cell Number",
  authenticatorApp: "Authenticator App",
  language: "Language",
  region: "Region",
  startOfWeek: "Start of week calendar",
  monday: "Monday",
  sunday: "Sunday",
  editProject: "Edit Project",
  hourFormat: "Hour Format",
  dateFormat: "Date Format",
  newHouse: "New House",
  activityHistory: "Activity History",
  timeline: "Timeline",
  files: "Files",
  tasks: "Tasks",
  overview: "Overview",
  budgets: "Budgets",
  details: "Details",
  edit: "Edit",
  projectDescription:
    "Lacinia at aenean lorem ipsum elementum senectus vitae eros. At fringilla fermentum, lobortis neque malesuada nulla ut aenean risus.",
  teamMembers: "Team Members",
  currentEstimatedBudgets: "Current Estimated Budget",
  seeAll: "See All",
  lastUpdates: "Last Updates",
  discussion: "Discussion",
  comment: "comment",
  linksAndFiles: "Links And Files",
  addNew: "Add New",
  addNewTask: "Add New Task",
  addNewFile: "Add New File",
  fileName: "File Name",
  documentType: "Document Type",
  fileType: "(.jpeg, .pdf, .doc, .mp4, .mov and url)",
  add: "Add",
  description: "Description",
  who: "Who",
  uploadDate: "Upload Date",
  dollarAmount: "Dollar Amount",
  amount: "Amount",
  asOf: "As of",
  changePassword: "Change Password",
  confirmPassword: "Confirm Password",
  oldPassword: "Old Password",
  loremipsum:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lorem ipsum, faucibus ut ultricies a, suscipit et lacus. Etiam maximus et nulla ac hendrerit. Aliquam vehicula mattis quam, id suscipit nisi congue sed.",
  attachments: "Attachments",
  downloadAll: "Download all",
  dropfileshere: "Upload files here to attach or",
  browse: "browse",
  changeEmail: "Change Email",
  finalDate: "Final Date",
  taskName: "Task Name",
  canTheClientSeeTheTask: "Can the client see the task?",
  canTheContributorSeeTheTask: "Can the Contributor see the task?",
  signupSuccessfull: "Signup Successfull!",
  signupFailed: "Signup Failed!",
  signinSuccessfull: "Signin Successfull!",
  signinFailed: "Signin Failed!",
  otpsentsuccess: "Otp Sent Successfull!",
  forgetPasswordEmailSent: "Forget Password Email Sent!",
  forgetPasswordEmailSentFailed: "Forget Password Email Sent Failed!",
  verificationSuccess: "Verification Successfull!",
  verificationFailed: "Verification Failed, Try Again!",
  socialSignupSuccess: "Social Signup Success!",
  socialSignupFailed: "Social Signup Failed, Try Again",
  resetPasswordSuccessFull: "Change Password Successfull!",
  codeResendSuccess: "Code Resend Successfull!",
  addUserSuccess: "User Added Successfull!",
  projectNameIsRequired: "Project name is required",
  projectStartDateIsRequired: "Project start date is required",
  projectDueDateIsRequired: "Project due date is required",
  projectClientNameIsRequired: "Client name is required",
  projectMemberIsRequired: "Add member is required",
  projectDescriptionIsRequired: "Description is required",
  projectStatusIsRequired: "Project status is required",
  selectroleplease: "Select a role for user",
  updateYourAddress: "Update Your Address",
  updateYourPostal: "Update your Postal Code",
  updateYourState: "Update your State",
  updateYourCity: "Update your city",
  userUpdatedSuccess: "User Updated Successfull!",
  editUser: "Edit User",
  sendTo: "Sent to:",
  updateUser: "Update User",
  notifications: "Notifications",
  changePasswordSuccess: "Change Password Successfull!",
  userMsg:
    "lorem ipsum elementum senectus vitae eros. At fringilla fermentum, lobortis neque malesuada nulla ut aenean",
  recieveTime: "08:00PM",
  selectdifferentrole: "Select different role for user!",
  editUserSuccess: "User Edited Successfully!",
  stateName: "State Name",
  updateFullName: "Update Full Name",
  deny: "Deny",
  approve: "Approve",
    login: 'login',
    signIn: "Sign In",
    welcomeBack: "Welcome Back",
    PleaseEnterYourDetails: "Please, enter your details.",
    email: "Email",
    cancel: "Cancel",
    password: "Password",
    forgetPassword: "Forgot password?",
    orContinueWith: "Or continue with",
    SignUp: "sign up",
    dontHaveAnAccount: "Don’t have an account?",
    contributor: "Contributor",
    measure: "Measure (Units)",
    url: "Url",
    clickHereSeeBudget: "Click Here to see Budget",
    name: "Name",
    projectMember: "Project Member",
    addClient: "Add Clients",
    addNewBudget: "Add New Budget",
    attachment: "Attachment",
    addFileAttachment: "Add File Attachment (Optional)",
    loadMore: "Load More",
    createYourAccount: "Create your account",
    areYouSureYouWantToDelete: "Are you sure you want to delete this project?",
    areYouSureYouWantToDeleteUser: "Are you sure you want to delete this user?",
    areYouSureYouWantToDeleteTask: "Are you sure you want to delete this task?",
    pleaseenteryourdetails: "Please, enter your information to sign up",
    alreadyhaveaccount: "Already have an account?",
    enteryouremailtorecieveverification: "Please, enter your email address to receive a verification code",
    backToLogin: "Back To Log In",
    send: "Send",
    changeStatusSuccess: "Changed Status Successfully!",
    resendCode: "Resend Code",
    dateError: "Start date can't be greater than due date.",
    newEmail: "Type new Email",
    budgetDescription: "Description",
    budgetAmount: "Amount",
    delete: "Delete",
    verify: "verify",
    verifyemail: "Verify Your Email",
    socialLoginSuccessfull: "Social Login Successfull!",
    invalidURL: "Invalid Url",
    save: 'Save',
    editTask: "Edit Task",
    activity: "Activity",
    pleaseenterthecodesentto: "Please, enter the 4 digit code sent to",
    verifyemailsend: "johndoe@soloway.com",
    createNewPassword: "Create New Password",
    yournewPasswordMustcontain: "Your new password must contain at least 8 characters containing both letters and numbers.",
    newPassword: "New Password",
    confirmationPassword: "Confirmation Password",
    resetPassword: "Reset Password",
    enterYourEmail: "Enter your email",
    success: "Success",
    yourPasswordhasBeenReset: "Your password has been successfully reset",
    all: "All",
    inProgress: "In Progress",
    blocked: "Blocked",
    completed: "Completed",
    users: "Users",
    user: "User",
    newUser: "New User",
    search: "Search",
    assign: "Assign",
    addNewUser: "Add New User",
    otpSendtoEmail: "OTP was sent to your email!",
    addNewProject: "Add New Project",
    firstName: "First Name",
    lastName: "Last Name",
    role: "Role",
    userName: "User Name",
    sendInvite: "Send Invite",
    seanKingstom: "Sean Kingstom",
    noInternetConnection: "No Internet Connection",
    admin: "Admin",
    client: "Client",
    actions: "Actions",
    yourFullName: "Your Full Name",
    member: "Member",
    soloway: "Soloway",
    tucson: "Tucson",
    evoDesign : "Evo Design",
    filter: "Filter",
    taskTitle: "Task Title",
    responsible: "Responsible",
    status: "Status",
    notStarted: "Not Started",
    startDate: "Start Date",
    clearAll: "Clear All",
    saveFilters: "Save Filters",
    logOutSuccess: "Logout Success",
    project: "Projects",
    newProject: "New Project",
    projectName: "Project Name",
    dueDate: "Due Date",
    clientName: "Client Name",
    create: "Create",
    addMembers: "Add members",
    yourEmail: "Your Email",
    changeView: "Change View",
    Blocked: "Blocked",
    assignee: "Assignee",
    comments: "Comments",
    estimatedCompletion: "Estimated Completion",
    newHouseProject: "New House Project",
    saveChanges: "Save Changes",
    setting: "Setting",
    profile: "Profile",
    preferences: "Preferences",
    personalInfo: "Personal Information",
    userEmail: "sean@soloway.com",
    address: "Address",
    userAddress: "User Address",
    postalCode: "Postal Code",
    cityName: "City Name",
    countryName: "Country Name",
    twoFactorAuthentication: "2-factor Authentication",
    cellNo: "Cell Number",
    authenticatorApp: "Authenticator App",
    language: "Language",
    region: "Region",
    startOfWeek: "Start of week calendar",
    monday: "Monday",
    sunday: "Sunday",
    editProject: "Edit Project",
    hourFormat: "Hour Format",
    dateFormat: "Date Format",
    newHouse: "New House",
    activityHistory: "Activity History",
    timeline: "Timeline",
    files: "Files",
    tasks: "Tasks",
    overview: "Overview",
    budgets: "Budgets",
    details: "Details",
    edit: "Edit",
    projectDescription: "Lacinia at aenean lorem ipsum elementum senectus vitae eros. At fringilla fermentum, lobortis neque malesuada nulla ut aenean risus.",
    teamMembers: "Team Members",
    currentEstimatedBudgets: "Current Estimated Budget",
    seeAll: "See All",
    lastUpdates: "Last Updates",
    discussion: "Discussion",
    comment: "comment",
    linksAndFiles: "Links And Files",
    addNew: "Add New",
    addNewTask: "Add New Task",
    addNewFile: "Add New File",
    fileName: "File Name",
    documentType: "Document Type",
    fileType: "(.jpeg, .pdf, .doc, .mp4, .mov and url)",
    add: "Add",
    description: "Description",
    who: "Who",
    uploadDate: "Upload Date",
    dollarAmount: "Dollar Amount",
    asOf: "As of",
    changePassword: "Change Password",
    confirmPassword: "Confirm Password",
    oldPassword: "Old Password",
    loremipsum: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lorem ipsum, faucibus ut ultricies a, suscipit et lacus. Etiam maximus et nulla ac hendrerit. Aliquam vehicula mattis quam, id suscipit nisi congue sed.",
    attachments: "Attachments",
    downloadAll: "Download all",
    dropfileshere: "Upload files here to attach or",
    browse: "browse",
    changeEmail: "Change Email",
    finalDate: "Final Date",
    taskName: "Task Name",
    canTheClientSeeTheTask: "Can the client see the task?",
    canTheContributorSeeTheTask: "Can the Contributor see the task?",
    signupSuccessfull: "Signup Successfull!",
    signupFailed: "Signup Failed!",
    signinSuccessfull: "Signin Successfull!",
    signinFailed: "Signin Failed!",
    otpsentsuccess: "Otp Sent Successfull!",
    forgetPasswordEmailSent: "Forget Password Email Sent!",
    forgetPasswordEmailSentFailed: "Forget Password Email Sent Failed!",
    verificationSuccess: "Verification Successfull!",
    verificationFailed: "Verification Failed, Try Again!",
    socialSignupSuccess: "Social Signup Success!",
    socialSignupFailed: "Social Signup Failed, Try Again",
    resetPasswordSuccessFull: "Change Password Successfull!",
    codeResendSuccess: "Code Resend Successfull!",
    addUserSuccess: "User Added Successfull!",
    projectNameIsRequired: "Project name is required",
    projectStartDateIsRequired: "Project start date is required",
    projectDueDateIsRequired: "Project due date is required",
    projectClientNameIsRequired: "Client name is required",
    projectMemberIsRequired: "Add member is required",
    projectDescriptionIsRequired: "Description is required",
    projectStatusIsRequired: "Project status is required",
    selectroleplease: "Select a role for user",
    updateYourAddress: "Update Your Address",
    updateYourPostal: "Update your Postal Code",
    updateYourState: "Update your State",
    updateYourCity: "Update your city",
    userUpdatedSuccess: "User Updated Successfull!",
    editUser: "Edit User",
    updateUser: "Update User",
    notifications: "Notifications",
    changePasswordSuccess: "Change Password Successfull!",
    userMsg: "lorem ipsum elementum senectus vitae eros. At fringilla fermentum, lobortis neque malesuada nulla ut aenean",
    recieveTime: "08:00PM",
    selectdifferentrole: "Select different role for user!",
    editUserSuccess: "User Edited Successfully!",
    stateName: "State Name",
    updateFullName: "Update Full Name",
};
